# Site settings
title:       Log
description: "Development diary of J"

defaults:
  -
    values:
      layout: "default"

permalink: /:title/

paginate: 10
paginate_path: "/single/"

collections:
  my_categories:
    output: true
    permalink: /category/:name/
